#!/bin/bash

echo "-------------WELCOME TO YOUR NCI FARMERS' MARKET--------------"
echo ""
echo ""
echo "---------------------------WHO ARE WE?------------------------"
echo ""
echo "NIC Farmers' Market is a non GMO based fresh produced retail organization"
echo "that has been around for two decades. We sell only the best grade of"
echo "fresh greens, beans, potatoes, tomatoes and corn, each produce product"
echo "coming in a variety of choices. From the beginning of our existence,"
echo "we have never treated any of our products with pesticides. Growing"
echo "everything organically is our mission to bring you the best quality"
echo "of produce."
echo ""
echo "Here are the choices of products you can select from:"
echo ""
echo "1) Greens- Kale, Mustard or Turnip"
echo ""
echo "2) Beans- Pinto, Green or Lima"
echo ""
echo "3) Potatoes- Idaho, Russet or Sweet"
echo ""
echo "4) Tomatoes- Regular, Roma or Cherry"
echo ""
echo "5) Corn- Yellow or White"
echo ""
echo ""
echo "ALL CUSTOMERS HAVE THE OPPORTUNITY OF JOINING OUR MEMERSHIP PROGRAM:"
echo "Our membership program allows customers to recieve 10% off $20"
echo "purchase or more."
echo ""
echo "You can join today! Choose now to become a member!!!"
echo ""
echo "To join now, Please enter, your first and last name, phone number"
echo "and address below."
sleep 3
echo ""
echo ""
read -p "What is your first name? >> " first_name
read -p "what is your last name? >> " last_name
read -p "what is your phone number? >> " Phone_number 
read -p "what is your address? >> " address
echo "" 
echo "Thank you for joining, $first_name $last_name"
