#!/bin/bash

echo "🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎"
echo "                                                                        "
printf "\33[32m"
echo "*                    ⢀⡴⠑⡄⠀⠀⠀⠀⠀⠀⠀⣀⣀⣤⣤⣤⣀⡀⠀⠀⠀⠀                            *"
echo "*                    ⠸⡇⠀⠿⡀⠀⠀⠀⣀⡴⢿⣿⣿⣿⣿⣿⣿⣿⣷⣦⡀⠀⠀                           *"
echo "*                    ⠀⠀⠀⠀⠑⢄⣠⠾⠁⣀⣄⡈⠙⣿⣿⣿⣿⣿⣿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀                     *"
echo "*                    ⠀⠀⠀⠀⢀⡀⠁⠀⠀⠈⠙⠛⠂⠈⣿⣿⣿⣿⣿⠿⡿⢿⣆⠀⠀⠀⠀⠀⠀⠀                    *"
echo "*                    ⠀⠀⠀⢀⡾⣁⣀⠀⠴⠂⠙⣗⡀⠀⢻⣿⣿⠭⢤⣴⣦⣤⣹⠀⠀⠀⢀⢴⣶⣆                    *"
echo "*                    ⠀⠀⢀⣾⣿⣿⣿⣷⣮⣽⣾⣿⣥⣴⣿⣿⡿⢂⠔⢚⡿⢿⣿⣦⣴⣾⠁⠸⣼⡿                    *"
echo "*                    ⠀⢀⡞⠁⠙⠻⠿⠟⠉⠀⠛⢹⣿⣿⣿⣿⣿⣌⢤⣼⣿⣾⣿⡟⠉⠀⠀⠀⠀⠀                    *"
echo "*                    ⠀⣾⣷⣶⠇⠀⠀⣤⣄⣀⡀⠈⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀                    *"
echo "*                    ⠀⠉⠈⠉⠀⠀⢦⡈⢻⣿⣿⣿⣶⣶⣶⣶⣤⣽⡹⣿⣿⣿⣿⡇⠀       ⠀⠀⠀⠀⠀             *"
echo "*                    ⠀⠀⠀⠀⠀⠀⠀⠉⠲⣽⡻⢿⣿⣿⣿⣿⣿⣿⣷⣜⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀                    *"
echo "*                    ⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣷⣶⣮⣭⣽⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀                     *"
echo "*                    ⠀⠀⠀⠀⠀⠀⣀⣀⣈⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀                       *"
echo "*                    ⠀⠀⠀⠀⠀⠀⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀                        *"
echo "*                    ⠀⠀⠀⠀⠀⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠟⠁⠀⠀⠀⠀⠀⠀⠀                      *"
echo "*                    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⠻⠿⠿⠿⠿⠛                                 *"
printf "\33[0m"
echo "-------------WELCOME TO YOUR NCI FARMERS' MARKET--------------"
echo ""
#sleep 2
echo ""
echo "---------------------------WHO ARE WE?------------------------"
echo ""
echo "NCI Farmers' Market is a non GMO based fresh produced retail organization"
echo "that has been around for two decades. We sell only the best grade of"
echo "fresh greens, beans, potatoes, tomatoes and corn, each produce product"
echo "coming in a variety of choices. From the beginning of our existence,"
echo "we have never treated any of our products with pesticides. Growing"
echo "everything organically is our mission to bring you the best quality"
echo "of produce."
#sleep 10
echo ""
echo "Here are the choices of products you can select from:"
echo ""
echo "-------------------------------PRODUCE ID----------------------"
echo ""
echo "1) Greens"
echo "2) Beans"
echo "3) Potatoes"
echo "4) Tomatoes"
echo "5) Corn"
#sleep 2
echo ""
echo ""
echo "ALL CUSTOMERS HAVE THE OPPORTUNITY OF JOINING OUR MEMERSHIP PROGRAM:"
echo "Our membership program allows customers to recieve 10% off of any"
echo "puchase on any combiantion of products"
echo " "
echo "🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎"
