#!/bin/bash

#while true; do

echo "🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎"
printf "\33[34m"
echo "------------------------------------------------------------------------"
printf "\33[33m"
echo "************************< NCI FARMERS MARKET >**************************"
printf "\33[34m"
echo "------------------------------------------------------------------------"
printf "\33[33m"
echo "                     Become A NFM GOLD Member Today!                    "
echo "                      Get Incredible Perks & Deals                      "
printf "\33[34m"
echo "------------------------------------------------------------------------"
printf "\33[33m"
echo "                            PERKS & DEALS                               "
echo "                                                                        "
printf "\33[34m"
echo "         SHIPPING                                DISCOUNTS              "
printf "\33[33m"
echo "   Free Standard Shipping.                 10% Off Final Purchase.      "
echo "                                                                        "
echo "                                                                        "
printf "\33[34m"
echo "        Health Facts                        Family Sharing PROGRAM      "
printf "\33[33m"
echo "     Healthy Recipe and                   Add up to 3 family members    "
echo "  meal planning tecniques.                  under your membership.      "
sleep 5
printf "\33[32m"
echo "                                                                        "
echo "                                        _/ .-...                        "
echo "                              _      _/. .  _..                         "
echo "                     ..:::::.(_)   /. _.._./                            "
printf "\33[31m"
echo "                   .oooooooooo\ \o/.-.__. o.                            "
echo "                  .ooooooooo.._\_|_...oooooob.                          "
echo "                 .ooooooooooooooooooooo&&oooooob.                       "
echo "                .oooooooooooooooooooo&@@@@@@oooob.                      "
echo "               .ooooooooooooooooooooooo&&@@@@@ooob.                     "
echo "               doooooooooooooooooooooooooo&@@@@ooob                     "
echo "               doooooooooooooooooooooooooo&@@@oooob                     "
echo "               dooooooooooooooooooooooooo&@@@ooooob                     "
echo "               doooooooooooooooooooooooo&@@oooooob                      "
echo "               dooooooooooooooooooooooooo&@ooooob                       "
echo "                doooooooooooooooooooooooooooooob                        "
echo "                 doooooooooooooooooooooooooooob                         "
echo "                  doooooooooooooooooooooooooob                          "
echo "                   doooooooooooooooooooooooob                           "
echo "                    doooooooooooooooooooooob                            "
echo "                     dooooooooobodoooooooob                             "
echo "                      doooooooob dooooooob                              "
echo "                                                                        "
echo "🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎🍌🍎"
