#!/bin/bash

#while true; do

echo "------------------------------------------------------------------------"
echo "************************< NCI FARMERS MARKET >**************************"
echo "------------------------------------------------------------------------"
echo "                     Become A NFM GOLD Member Today!                    "
echo "                      Get Incredible Perks & Deals                      "
echo "------------------------------------------------------------------------"
echo "                            PERKS & DEALS                               "
echo "                                                                        "
echo "         SHIPPING                                DISCOUNTS              "
echo "   Free Standard Shipping.                 10% Off Final Purchase.      "
echo "                                                                        "
echo "                                                                        "
echo "        Health Facts                        Family Sharing PROGRAM      "
echo "     Healthy Recipe and                   Add up to 3 family members    "
echo "  meal planning tecniques.                  under your membership.      "
sleep 5
printf "\33[31m"
echo "                                                                        "
echo "                                        _/ .-...                        "
echo "                              _      _/. .  _..                         "
echo "                     ..:::::.(_)   /. _.._./                            "
echo "                   .oooooooooo\ \o/.-.__. o.                            "
echo "                  .ooooooooo.._\_|_...oooooob.                          "
echo "                 .ooooooooooooooooooooo&&oooooob.                       "
echo "                .oooooooooooooooooooo&@@@@@@oooob.                      "
echo "               .ooooooooooooooooooooooo&&@@@@@ooob.                     "
echo "               doooooooooooooooooooooooooo&@@@@ooob                     "
echo "               doooooooooooooooooooooooooo&@@@oooob                     "
echo "               dooooooooooooooooooooooooo&@@@ooooob                     "
echo "               doooooooooooooooooooooooo&@@oooooob                      "
echo "               dooooooooooooooooooooooooo&@ooooob                       "
echo "                doooooooooooooooooooooooooooooob                        "
echo "                 doooooooooooooooooooooooooooob                         "
echo "                  doooooooooooooooooooooooooob                          "
echo "                   doooooooooooooooooooooooob                           "
echo "                    doooooooooooooooooooooob                            "
echo "                     dooooooooobodoooooooob                             "
echo "                      doooooooob dooooooob                              "
echo "------------------------------------------------------------------------"
sleep 2
echo "                                                                        "
echo "                                                                        "
echo "                                                                        "
echo "************************************************************************"
echo "                                                                        "
echo "                       Weclome to the NFM Family!                       "
echo "                   You are Offically a NFM Gold Member!                 "
echo "                     Enjoy Incredible Perks & Deals                     "
echo "                                                                        "
echo "                                                                        "
sleep 5
echo "************************************************************************"
echo "*  NCI MARKET GOLD MEMBER                                              *"
sleep 2
printf "\33[32m"
echo "*                                                                      *"
echo "*                    ⢀⡴⠑⡄⠀⠀⠀⠀⠀⠀⠀⣀⣀⣤⣤⣤⣀⡀⠀⠀⠀⠀                            *"
echo "*                    ⠸⡇⠀⠿⡀⠀⠀⠀⣀⡴⢿⣿⣿⣿⣿⣿⣿⣿⣷⣦⡀⠀⠀                           *"
echo "*                    ⠀⠀⠀⠀⠑⢄⣠⠾⠁⣀⣄⡈⠙⣿⣿⣿⣿⣿⣿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀                     *"
echo "*                    ⠀⠀⠀⠀⢀⡀⠁⠀⠀⠈⠙⠛⠂⠈⣿⣿⣿⣿⣿⠿⡿⢿⣆⠀⠀⠀⠀⠀⠀⠀                    *"
echo "*                    ⠀⠀⠀⢀⡾⣁⣀⠀⠴⠂⠙⣗⡀⠀⢻⣿⣿⠭⢤⣴⣦⣤⣹⠀⠀⠀⢀⢴⣶⣆                    *"
echo "*                    ⠀⠀⢀⣾⣿⣿⣿⣷⣮⣽⣾⣿⣥⣴⣿⣿⡿⢂⠔⢚⡿⢿⣿⣦⣴⣾⠁⠸⣼⡿                    *"
echo "*                    ⠀⢀⡞⠁⠙⠻⠿⠟⠉⠀⠛⢹⣿⣿⣿⣿⣿⣌⢤⣼⣿⣾⣿⡟⠉⠀⠀⠀⠀⠀                    *"
echo "*                    ⠀⣾⣷⣶⠇⠀⠀⣤⣄⣀⡀⠈⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀                    *"
echo "*                    ⠀⠉⠈⠉⠀⠀⢦⡈⢻⣿⣿⣿⣶⣶⣶⣶⣤⣽⡹⣿⣿⣿⣿⡇⠀       ⠀⠀⠀⠀⠀             *"
echo "*                    ⠀⠀⠀⠀⠀⠀⠀⠉⠲⣽⡻⢿⣿⣿⣿⣿⣿⣿⣷⣜⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀                    *"
echo "*                    ⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣷⣶⣮⣭⣽⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀                     *"
echo "*                    ⠀⠀⠀⠀⠀⠀⣀⣀⣈⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀       < USERNAME >    *"
echo "*                    ⠀⠀⠀⠀⠀⠀⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀       < EXP: 1 YEAR >  *"
echo "*                    ⠀⠀⠀⠀⠀⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠟⠁⠀⠀⠀⠀⠀⠀⠀                      *"
echo "*                    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⠻⠿⠿⠿⠿⠛                                 *"
echo "************************************************************************"
sleep 2
printf "\33[33m"
echo "   //\                                                                  "
echo "   V  \                                                                 "
echo "    \  \_  Membership is good for one year after joining.               "
echo "     \,..-.       Enjoy your NFM Gold Membership!                       "
echo "      |\ . ..                                                           "
echo "      ( \  . -.                        _,.-.\                           "
echo "       \ \   . . -._             __..-- ,-./                            "
echo "        \ .   -.   -..___..---   _.--. ,./                              "
echo "         . ..    -._        __..--  . , /                               "
echo "           .. -_     --..       _.- .,.                                 "
echo "            -_ -.___        __,--   ,.                                  "
echo "                -.__  ----    __.-                                      "
echo "                     --..____..--                                       "


