#!/bin/bash

#while true; do

echo "------------------------------------------------------------------------"
echo "                                                                        "
echo "************************< NCI FARMERS MARKET >**************************"
echo "                                                                        "
echo "------------------------------------------------------------------------"
echo "                                                                        "
echo "                     Become A NFM GOLD Member Today!                    "
echo "                      Get Incredible Perks & Deals                      "
echo "                                                                        "
echo "------------------------------------------------------------------------"
echo "                                                                        "
sleep 3
echo "------------------------------------------------------------------------"
echo "                                                                        "
echo "                       Weclome to the NFM Family!                       "
echo "                   You are Offically a NFM Gold Member!                 "
echo "                     Enjoy Incredible Perks & Deals                     "
echo "                                                                        "
echo "************************************************************************"
echo "                    ⢀⡴⠑⡄⠀⠀⠀⠀⠀⠀⠀⣀⣀⣤⣤⣤⣀⡀⠀⠀⠀⠀       NCI MARKET GOLD MEMBER "
echo "                    ⠸⡇⠀⠿⡀⠀⠀⠀⣀⡴⢿⣿⣿⣿⣿⣿⣿⣿⣷⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀                      "
echo "                    ⠀⠀⠀⠀⠑⢄⣠⠾⠁⣀⣄⡈⠙⣿⣿⣿⣿⣿⣿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀                      "
echo "                    ⠀⠀⠀⠀⢀⡀⠁⠀⠀⠈⠙⠛⠂⠈⣿⣿⣿⣿⣿⠿⡿⢿⣆⠀⠀⠀⠀⠀⠀⠀                      "
echo "                    ⠀⠀⠀⢀⡾⣁⣀⠀⠴⠂⠙⣗⡀⠀⢻⣿⣿⠭⢤⣴⣦⣤⣹⠀⠀⠀⢀⢴⣶⣆                      "
echo "                    ⠀⠀⢀⣾⣿⣿⣿⣷⣮⣽⣾⣿⣥⣴⣿⣿⡿⢂⠔⢚⡿⢿⣿⣦⣴⣾⠁⠸⣼⡿                      "
echo "                    ⠀⢀⡞⠁⠙⠻⠿⠟⠉⠀⠛⢹⣿⣿⣿⣿⣿⣌⢤⣼⣿⣾⣿⡟⠉⠀⠀⠀⠀⠀                      "
echo "                    ⠀⣾⣷⣶⠇⠀⠀⣤⣄⣀⡀⠈⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀                      "
echo "                    ⠀⠉⠈⠉⠀⠀⢦⡈⢻⣿⣿⣿⣶⣶⣶⣶⣤⣽⡹⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀                      "
echo "                    ⠀⠀⠀⠀⠀⠀⠀⠉⠲⣽⡻⢿⣿⣿⣿⣿⣿⣿⣷⣜⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀                      "
echo "                    ⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣷⣶⣮⣭⣽⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀                       "
echo "                    ⠀⠀⠀⠀⠀⠀⣀⣀⣈⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀     < USERNAME >     "
echo "                    ⠀⠀⠀⠀⠀⠀⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀    < EXP: 1 YEAR >   "
echo "                    ⠀⠀⠀⠀⠀⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠟⠁⠀⠀⠀⠀⠀⠀⠀                        "
echo "                    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⠻⠿⠿⠿⠿⠛                                   "
echo "************************************************************************"
sleep 3
echo "                                                                        "
echo "                            PERKS & DEALS                               "
echo "                                                                        "
echo "         SHIPPING                                DISCOUNTS              "
echo "   Free Standard Shipping.               10%-20% Off Final Purchase.    "
echo "                                                                        "
echo "                                                                        "
echo "        Health Facts                           SAVINGS PROGRAM          "
echo "     Healthy Recipe and                  Get 2% Back on Qualifying      "
echo "   meal planning tecniques.                      Purchases.             "
echo "                                                                        "
echo "                                                                        "
echo "                                                                        "
echo "                                                                        "
echo "           Membership is good for one year after joining.               "
echo "     Welcome to the family! You are now offically a NFM Gold Member     "
echo "                                                                        "
#done
echo " "
